### ISSUE TITLE
Product case studies: As a government user reviewing cloud products, I want to identify other government agencies that have used the cloud service, so that I don't feel like my agency is exploring a non-workable solution or the first to use.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#100]
As a government user reviewing cloud products, I want to identify other government agencies that have used the cloud service, so that I can demonstrate to internal stakeholders that we are not the first to use (if applicable).

## Notes
Government users don't want to be the first to try something, so information will help build confidence.

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] 

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Refer to corresponding FedRAMP API data point
- [ ] Product page will include a section called " Agencies using:"
- [ ] A bulleted list of the agency icon and or name will be included in the " Agencies using:" list

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jenniferthibault** [comment]
Moving to the icebox for a future phase — though case studies are a highly sought user resource, we don't currently have content from a neutral perspective for these items. We may be able to access vendor case studies in the future, but would need considerable editing to change the tone from a marketing piece to an informational piece.
