### ISSUE TITLE
As a government user considering cloud products, I would like to access case studies that highlight how other government agencies have procured a particular cloud service, so that I can demonstrate to internal stakeholders that we are not the first to use the service/product (if applicable).

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#101]
As a government user considering cloud products, I would like to access case studies that highlight how other government agencies have procured a particular cloud service, so that I can demonstrate to internal stakeholders that we are not the first to use the service/product (if applicable).

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] x

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] User can access relevant case study about the product/service via a hyperlink from the products page underneath the product description
- [ ] Case study hyperlink will open a pdf document that can be downloaded or saved

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users
