### ISSUE TITLE
As a government user on the CIC site, I want to be able to access and download all the relevant acquisition template files in one place, so that I can use standardized files that will have all the information I need to begin the acquisition process.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#102]
As a government user on the CIC site, I want to be able to access and download all the relevant acquisition template files in one place, so that I can use standardized files that will have all the information I need to begin the acquisition process.

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] x

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] All the the relevant acquisition template files will be accessible from the Acquisition > Template page.
- [ ] Users will be able to open or download the acquisition template files

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jenniferthibault** [comment]
Closing in favor of more specific template breakdowns in #47 & #48
