### ISSUE TITLE
In order to balance UX with content, test long and short page content to understand word limits

### ISSUE THREAD

**Issue by abbeykos** [18F/cic-site#104]
## Notes
Our site design will accommodate an infinite amount of content, but there are limits (both short and long) in which the site will look and operate effectively. To understand those limits, we should test long and short proposed pages so we know how to tweak content and/or design as necessary.

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Develop "short" and "long" page content (i.e., actual pages that have either a lot or a little to communicate
- [ ] Test that content in Invision
- [ ] Examine layout and decide on next steps for tweaking content or design as appropriate

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Long and short pages have been drafted
- [ ] Long and short pages have been tested
- [ ] We know our word limits

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users
