### ISSUE TITLE
Why cloud – Basics: As a govt user, I want a basic understanding of cloud so that I can make an informed buying choice

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#107]
Breakdown of #68

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [x] Synthesize existing content & write draft
- [x] Move content from wireframe to site
- [x] update the site nav (if necessary?)
- [x] update layouts

_Acceptance criteria define when a work item is complete and working as expected._
- [x] I can read a basic understanding of cloud 

## Definition of done
- [x] Acceptance criteria met
- [x] Code, design, or content reviewed by team members

**Comment by jdamis4XD** [comment]
Content ported into Federalist, but Abbey wants to revisit again later.

**Comment by jenniferthibault** [comment]
Added via #119
