### ISSUE TITLE
As a member of the site team, I want to measure whether the IA is successfully meeting user needs so that we can make changes if necessary

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#109]
Since we are having trouble recruiting card sort and tree test users, we are looking for other ways of measuring success of the site IA, including possibly a site intercept, as seen on GSA.gov. This will help gather feedback for the next round of changes, (or next phase of work, if it comes too late).

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [x] Research how we get access to an intercept tool 
- [x] Secure access to intercept tool
- [x] Decide what logic will trigger the intercept
- [x] Determine if an automated response report can be setup to track feedback 
- [x] Write content framing feedback
- [ ] Implement intercept logic on the production site

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] We are able to get feedback on the site's IA asynchronously
- [ ] Feedback is collected, stored and accessible either from a table or an auto generated report

**Comment by jdamis4XD** [comment]
Met with Lauren and Ryan in order to launch next week if the site **will not** be available to the public than we don't have to be PRA compliant and can have more 3- 5 questions.  If PRA compliance is required, than we will be limited to a generic open ended question, like the https://www.farmers.gov/. @lauraGgit will the MVP site be accessible to the public?

**Comment by jdamis4XD** [comment]
@lauraGgit Lauren Ancona provided the following Google Snippet and instructions on how to add to the site:

// Add the below snippet in <head>

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PJCSB98');</script>

	
// Add the below snippet as high in <body> as possible

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PJCSB98"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by jdamis4XD** [comment]
@lauraGgit Lauren will need to be informed once the code is added to test on her end.  If a question needs to be updated we will need to let Lauren know who will need a day or two to implement.

**Comment by jenniferthibault** [comment]
Quick question on this — even though the site isn't "public" as in, connected from GSA and marketed/promoted, it's still publicly findable. Can't tell from the thread here, but did the content in (this comment)[https://github.com/18F/cic-site/issues/109#issuecomment-421121968] change based on that access?

**Comment by jdamis4XD** [comment]
We are going to have two branches, one that is password protected and will have the survey and another that is public facing with no survey.

Final questions are:
Survey fields (password protected site):
1- [1-5 rating] How would you rate the site navigation menus?
2- [ Open ended] Are there any improvements you would like to see of how navigation is organized? (Please explain)
3- [Y/N] Were you able to find the content you needed on the site?
4 - [Open ended] Is there anything else you want to share?
