### ISSUE TITLE
Impl - Staffing resources: In order to build a team capable of managing our initiatives, as a CIO/CTO (or program manager) I want to know what skillsets I should have on my team.

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#112]
## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Synthesize existing content & write draft
- [ ] Move content from wireframe to site
- [ ] update the site nav (if necessary?)
- [ ] update layouts

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] I can read on the site an intro to what types of skillsets are necessary, and understand if there are obvious skills to outsource

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members

**Comment by lauraGgit** [comment]
Nav fixed page here: https://federalist-proxy.app.cloud.gov/preview/18f/cic-site/massive-build-day/implementation/business/staffing-resources/

**Comment by abbeykos** [comment]
4.2.1 Staffing resources has been reviewed, edited, updated, and is ready to go on the site.
