### ISSUE TITLE
Acq - Templates - SOW: As a program manager, I want an SOW template, so that I can use what's proven successful for the job, and don't have to start from scratch every time

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#113]
## Notes
Shared templates allow government program managers to more quickly begin their acquisition process, and help vendors respond to more uniform requests. 

## Tasks
- [ ] Define which examples are best in class, work with Skip
- [ ] Turn examples into templates — 
- [ ] Use what we learned in #48 to complete the following:
  - - [ ] Higher design fidelity design decisions  (icons)
  - - [ ] Implement new document layout
  - - [ ] Add asset capability for these documents (where do they even liiiive?)
  - - [ ] Generate data type to allow for easier adding of new document

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Template or example documents are defined and listed
- [ ] Template or example exists as a downloadable document

## Definition of done
- [ ] Acceptance criteria met
- [ ] Content reviewed by team members
- [ ] Reviewed with subject matter expert

**Comment by ColinChambers22** [comment]
[GSA eBuy Tutorial.pptx](https://github.com/18F/cic-site/files/2381688/GSA.eBuy.Tutorial.pptx)
[IGCE Template.xlsx](https://github.com/18F/cic-site/files/2381689/IGCE.Template.xlsx)
[USAID Guide on IGCE.pdf](https://github.com/18F/cic-site/files/2381690/USAID.Guide.on.IGCE.pdf)
[DAU 7 steps to create an SOW.pdf](https://github.com/18F/cic-site/files/2381691/DAU.7.steps.to.create.an.SOW.pdf)
I included the template for the SOW, but we probably want to add the SOO one from Skip. I also added all the other guidance I mentioned that should probably be in an IGCE section.
