### ISSUE TITLE
Acq - Templates - RFI: As a program manager, I want an RFI template, so that I can use what's proven successful for the job, and don't have to start from scratch every time

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#114]
## Notes
Shared templates allow government program managers to more quickly begin their acquisition process, and help vendors respond to more uniform requests. 

## Tasks
- [ ] Define which examples are best in class, work with Skip
- [ ] Turn examples into templates — 
- [ ] Use what we learned in #48 to complete the following:
  - - [ ] Higher design fidelity design decisions  (icons)
  - - [ ] Implement new document layout
  - - [ ] Add asset capability for these documents (where do they even liiiive?)
  - - [ ] Generate data type to allow for easier adding of new document

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Template or example documents are defined and listed
- [ ] Template or example exists as a downloadable document

## Definition of done
- [ ] Acceptance criteria met
- [ ] Content reviewed by team members
- [ ] Reviewed with subject matter expert
