### ISSUE TITLE
H tag font updated for the CIC sites

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#131]
As a [user or stakeholder type], I want [goal], so that [some reason/business value]

## Notes
Revisit updating the h tags for the site as the current <H1> - <H4> are kind of big and we would like to reduce the font sizes

https://github.com/uswds/uswds/blob/c98f69c879d0fc9e2e2cc72ee9ee9743c1971d39/src/stylesheets/core/_variables.scss#L14

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] H1 will now be H2 value
- [ ] H2 will now be H3 value and so forth

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] z

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users
