### ISSUE TITLE
As a site visitor, I want to see the primary and sub nav links of the site in the footer, so I don't have to interact with the site navs.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#138]
As a site visitor, I want to see the primary and sub nav links of the site in the footer, so I don't have to interact with the site navs.

## Notes
Refer to the big footer style in the USWDS found here, https://designsystem.digital.gov/components/footers/

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Add all the primary links from the global nav to the footer: Why Cloud, Find Cloud Solutions, Acquisition, Implementation and 
- [ ] Add the sub nav menu items for each nav section

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Global nav links and menu items visible from the footer
- [ ] All links take you relevant site pages

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jdamis4XD** [comment]
@lauraGgit Added the footer story
