### ISSUE TITLE
As a gov buyer, I want to know the maintenance required for the different cloud models, so that I can prepare for business and human resource costs.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#140]
As a gov buyer, I want to know the maintenance required for the different cloud models, so that I can prepare for business and human resource costs.

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Content for maintenance page is created

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] z

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jdamis4XD** [comment]
@abbeykos Added maintenance story, feel free to flush out.

**Comment by jenniferthibault** [comment]
Resolved by content added in #141
