### ISSUE TITLE
Imp - Scaling: As a gov user, I want know the different cloud scaling factors that I should be concerned about, so that adequately prepared to support the cloud technology for my agency.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#143]
As a gov user, I want know the different cloud scaling factors that I should be concerned about, so that adequately prepared to support the cloud technology for my agency.

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Content created
- [ ] Content added to the site

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] z

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jenniferthibault** [comment]
This looks like it was resolved by #144 , closing
