### ISSUE TITLE
As a gov user, I want to be aware of the business implications I should be considering when moving to the cloud, so that I can have a successful migration to cloud technology.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#150]
As a gov user, I want to be aware of the business implications I should be considering when moving to the cloud, so that I can have a successful migration to cloud technology.

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Content created
- [ ] Content added to the site

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] z

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jenniferthibault** [comment]
Added via #156
