### ISSUE TITLE
Impl Overview: As a gov user I want , I want to would like an implementation overview that covers the basics things to consider when migrating to the cloud, so that I am aware of the risks to plan for successful migration.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#153]
Impl Overview: As a gov user I want , I want to would like an implementation overview that covers the basics things to consider when migrating to the cloud, so that I am aware of the risks to plan for successful migration.

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Content created
- [ ] Content added to the site

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] z

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jenniferthibault** [comment]
Resolved by adding content in #154
