### ISSUE TITLE
As a team member, I want to know where the site will live so that we can start building toward a production-ready environment

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#37]
## Notes
So that the team can begin integrating the site to the technical and design environment it will live within, we need to learn what the production URL will be and understand the technical steps to get there. 

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] x

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] A production URL has been identified & agreed upon by team & stakeholders
- [ ] Follow-up issues have been created to identify technical and design steps to integrate the site to its new environment

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users (?)

**Comment by jenniferthibault** [comment]
Slight change of idea here — we think we should operate on the assumption of using the Federalist staging URL for now, and revisit this around 9/24 to see what our partners are comfortable with, in terms of finding a more production-oriented URL for a release at that point or not. 

@lauraGgit should we move this even more back into backlog and remove the Sprint 3 milestone?
