### ISSUE TITLE
As a user of the site I want to be directed to other existing resources at the right part in my journey

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#40]
## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Identify existing list for other cloud tools/resources
- [ ] Identify SMEs for those resources

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] z

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jenniferthibault** [comment]
Redundant to #46, closing
