### ISSUE TITLE
Test site architecture to determine if it matches users mental model

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#43]
As a site, a user will need to be able to successfully navigate across the site to learn about cloud tech and identify cloud solutions/products available to shop, so that their agency can successfully migrate to the cloud.

## Notes
[More detail on the user story]

## Tasks
_ [ ]Refine sitemap
- [ ]Create card sort to determine users info hierarchy understanding
- [ ]Tree test the information hierarchy

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Need feedback from more than 40 users for each user group

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jdamis4XD** [comment]
Recruitment email was sent to the DCOI listserv on Friday for permission to share the recruitment email with the list.  Abbey reached out to the contact for the Small and Micro Agency CISO council as well and we are waiting for response to share the recruitment email.

**Comment by jdamis4XD** [comment]
At the moment there are only two responses to the study.  Abbey recommended that if we get low response rates from the DCOI that we send an email blast to GSA staff as an alternate proxy group. Think we will need to go this route.

**Comment by jenniferthibault** [comment]
Sounds like it might be worth another nudge to the Small & Micro agency list, @abbeykos ?

Reaching out to GSA is do-able as a backup backup, but I'd be a little worried that it's not to our target users

**Comment by abbeykos** [comment]
Just poked Alen (keeper of The List). Will let you know when we hear back (@jdamis4XD is cc'ed).

Agreed that GSA/18F user testing is not ideal, but it may be less bad than it is on other projects because we're at least talking to federal employees with tech expertise...

...anyway, hope we don't need to do it!

**Comment by jdamis4XD** [comment]
As of this morning we only have 6 complete (5 who abandoned).  To date, the recruitment email was shared with the DCOI distribution list, usability test participants from the last round of testing, and the Acquisition Prod Marketing slack channel.  I am thinking we need to ask the stakeholders if they can assist with recruitment as an email from them rather than me might have more weight.

**Comment by jdamis4XD** [comment]
We have completed the task and synthesized data, but due to low response rate of 8 responses I recommend redoing in the next phase of the project in fiscal year 2019. : https://app.mural.co/t/gsa6/m/gsa6/1536765930390/c34115aa9a21dd99eeeb22926b292ff456081ccc
