### ISSUE TITLE
Update Wireframes

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#44]
Incorporate user feedback into next iteration of wirerames
## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Refine current wires to reflect feedback
- [ ] Create new page templates

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Wireframes have been updated and reviewed by team

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by jdamis4XD** [comment]
Invision prototype: https://gsa.invisionapp.com/share/6ENWHGL5DCJ#/318229905_Home

**Comment by jdamis4XD** [comment]
#43 is blocking the ability to finalize the wireframe categories.
