### ISSUE TITLE
In order to make the right decisions about cloud models, users need to understand the difference between service models (IaaS, PaaS, and SaaS).

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#52]
## Notes
Many sources of this information exist, but it's a foundational concept for acquiring & transforming cloud practices. We should help govt agencies understand these concepts in terms that make sense to them. 

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [x] Synthesize notes from other sources into recommended descriptions
- [x] Understand where in the site flow people need to learn this information

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [x] Explanatory concepts exist for IaaS, PaaS, SaaS
- [x] Content has been incorporated into site wireframes

## Definition of done
- [x] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Content placed in Basics page

**Comment by jenniferthibault** [comment]
Closing in favor of a more comprehensive build in #107
