### ISSUE TITLE
As a member of the product team, I want to take advantage of industry user research so that my UX/content is as user-centered as possible

### ISSUE THREAD

**Issue by abbeykos** [18F/cic-site#53]
As a member of the product team, I want to take advantage of industry user research so that my UX/content is as user-centered as possible

## Notes
Vendor partners are willing to share some of their user research insights on how they've optimized their layout/content for people learning about the cloud. We want to have a conversation with those vendors to see what they've learned works and doesn't work.

## Tasks
- Work with Colin to get a meeting on the calendar with AWS
- Synthesize notes from the call into learnings
- Get access to any documentation, if relevant

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] A conversation has been had with AWS
- [ ] We've synthesized what we've learned and made updates to our UX/content taxonomy as appropriate
- [ ] We've communicated this work to our larger team of stakeholders to demonstrate industry coordination

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users

**Comment by abbeykos** [comment]
We're having a meeting with Druva on Friday (waiting for Colin/their team to send invite)
No update on AWS
