### ISSUE TITLE
As a govt user, I want to know what to consider to make a good buying choice so that I can use my agency's resources wisely

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#68]
## Tasks
- [ ] Figure out where in sitemap/architecture this content fits appropriately
- [ ] Prioritize those pages within the sitemap to draft first
____[edit in progress]_____
- [ ] Draft the content
- [ ] Implement the content 
- [ ] Rationalize/edit content to fit within its context

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] A draft of the content has been written and is ready to move to the site
- [ ] Format of the content has been discussed with UX & page designs updated to reflect
- [ ] We've tracked what source content informed the draft

## Notes
This will be a synthesis of the existing, audited documents in a more user-centered way. 

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members

**Comment by jenniferthibault** [comment]
Closing in favor of more detailed issues in #105 #106 #107
