### ISSUE TITLE
Impl - Change mgmt: As a govt user, I want to find existing resources on change management, so that I feel prepared to get started

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cic-site#74]
## Notes
GSA's [Data Center Optimization Initiative](https://www.gsa.gov/technology/government-it-initiatives/data-center-optimization-initiative-dcoi) (DCOI) has existing resources on change management that can be pointed to at the best place in a govt user's journey to make use of existing guidance.

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [x] Update designs
- [ ] Move content from wireframe to site
- [x] update the site nav (if necessary?)
- [x] update layouts

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] I know that DCOI has resources on change management and can find them when I need them

Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
