### ISSUE TITLE
Set up a story map for CIC roadmap management

### ISSUE THREAD

**Issue by mogul** [18F/cic-site#8]
In order build alignment with our stakeholders around the work being envisioned and prioritized to meet user needs, and track top-level thinking around that vision, we want to establish a dedicated space for maintaining a story map.

*Acceptance Criteria*
- [ ] We've got a Mural space dedicated to the CIC project
- [ ] We've got a value-prop canvas template visible in the Mural
- [ ] We've got a story map skeleton (even if skimpy) visible in the Mural
- [ ] We've got links off of the Mural to delve further into materials generated/used in the process
