### ISSUE TITLE
In order to procure funding for continuing work on the CIC, we will write an EBC to be presented to FAS leadership

### ISSUE THREAD

**Issue by mogul** [18F/cic-site#97]
## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] The EBC defines the problem to be solved, rather than proscribing the form of the solution (eg "The lack of a solution in this area costs $XX to Y and Z every X months, so it's worth putting $WW over the next A months toward solving that"

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] x

## Resources
-  y

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users
