### ISSUE TITLE
As a government user unfamiliar with cloud models,  I want to quickly be able to learn about the what the different cloud models are from a product page, so that I don't have to navigate away from the product page to find the information.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#98]
As a government user unfamiliar with cloud models,  I want to quickly be able to learn about the what the different cloud models are from a product page, so that I don't have to navigate away from the product page to find the information.

## Notes
[More detail on the user story]

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Abbey needs to provide the abbreviate content for the information modal window

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] User will be able to click on a information icon
- [ ] The information icon will open a small modal window with either IaaS, SaaS, or PaaS description
- [ ] Modal window will close off hover
- [ ] Modal window will include a link to the Why Cloud page

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users
