### ISSUE TITLE
As a Cloud Customer stakeholder, I want to provide government users a way to learn about the specialties of the Vendor from the CIC site, so that government users can learn more about the vendors, cloud products and services, and their level of expertise.

### ISSUE THREAD

**Issue by jdamis4XD** [18F/cic-site#99]
As a Cloud Customer stakeholder, I want to provide government users a way to learn about the specialties of the Vendor from the CIC site, so that government users can learn more about the vendors, cloud products and services, and their level of expertise.

## Notes
Provide a way for government users to learn about vendors that doesn't distract from their primary goal of understanding available cloud products for their use.

## Tasks
_Any specific steps or tasks we want to make sure to do_
- [ ] Vendor content and format is still an unknown
- [ ] Determine what vendor content user would expect from the site in next round of user testing

## Resources
-  y

## Acceptance criteria
_Acceptance criteria define when a work item is complete and working as expected._
- [ ] Government users can access vendor information from the product page if they want
- [ ] Government users will remain on their primary task of viewing cloud products
- [ ] Vendor window will open in large modal window
- [ ] Modal window will contain a close [X] icon in the top upper right hand corner of the window

## Definition of done
- [ ] Acceptance criteria met
- [ ] Code, design, or content reviewed by team members
- [ ] Tested with users
